spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: master
    password: '1q2w3e4r!'
    url: jdbc:mysql://db-ccfu6.cdb.ntruss.com:3306/master
  jpa:
    show-sql: true
    hibernate:
      #테이블 자동생성
      ddl-auto: create
  profiles:
    active: dev
    include:
      - file-logging
server:
  ssl:
    key-store: devkey.p12
    key-store-type: PKCS12
    key-store-password: '1q2w3e4r!'
    key-alias: devkey
    port: 8443