spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interpark?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: testuser
    password: 001219
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
      show-sql: true